### ISSUE TITLE
CI/CD Pipeline

### ISSUE THREAD

**Issue by alexzhang1618** [cse110-fa22-group5/cse110-fa22-group5#30]
On GitHub Actions

Consider adding:
- Prettier for code formatting
- ESlint and CSSlint for linting
- Minification - Optional
- HTML validation
- JSdocs for doc generation
- Jest/puppeteer for unit & e2e testing
- Functional testing - optional

**Comment by ckckcake** [comment]
added css/html linting and jest test, currently implementing jsdoc auto gen to work with github actions
