### ISSUE TITLE
Link notes.html with backend

### ISSUE THREAD

**Issue by laurenkiyomi** [cse110-fa22-group5/cse110-fa22-group5#60]
**What you're currently working on:**
- Currently working on the main dashboard
**Description of problem/updates:**
- Edit notes page needs to populate json file with notes from local storage
- When a new note is created, the user is taken to the edit notes page
**What more left to do:**
- The edit notes page needs to handle creating space in local storage for a new note that is created
- Need to handle flow from main dashboard to edit notes page
- [x] Dashboard populates using the functions in noteStorage.js
- [x] On clicking on one of the dashboard rows, opens a note page with the uuid as a query param
  - When creating a dashboard row with the shadow DOM, set the link to be `.../index.html?uuid={uuid}`
  - We can get the uuid from the URL like so: https://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript
- [x] Making a new note navigates to `.../index.html` with no uuid set
  - To save the note here, call saveNoteToStorage with the uuid set as undefined and it will return the uuid to you
  - Then set the uuid in the page's query params (navigate to `.../index.html?uuid={uuid}`)
  - Deleting the page when the uuid is not set just returns to the dashboard
- [x] Using the uuid from the page, clicking save note on a page should save the note to storage.
- [x] Using the uuid from the page, clicking delete note on a page should delete the note and return to the dashboard

**Comment by alexzhang1618** [comment]
Closed in #80
