### ISSUE TITLE
Confirm delete/unsaved changes (Delete note and back arrow)

### ISSUE THREAD

**Issue by priyakumar0817** [cse110-fa22-group5/cse110-fa22-group5#85]
**Description of problem/updates:** We need error checks whenever the user decides to delete a note. ex: "Are you sure you want to delete this note?" For both delete note and the back arrow button, and anywhere else we may see fit.

**Comment by alexzhang1618** [comment]
To confirm leaving a page:
https://www.w3schools.com/jsref/met_win_confirm.asp
We might also want to add a little field that shows up when there are unsaved changes on a page
