### ISSUE TITLE
Require Title

### ISSUE THREAD

**Issue by laurenkiyomi** [cse110-fa22-group5/cse110-fa22-group5#97]
**Description of problem/updates:**
Right now users can have notes with no title
**What more left to do:**
Make title a required field. It shouldn't be allowed to be blank.

**Comment by alexzhang1618** [comment]
Also: Build the initial note with title: "", and have the title field placeholder be "Untitled Note"

**Comment by priyakumar0817** [comment]
Finished completing this issue, now need to update our E2E tests to match. Will be completed by tonight or tomorrow.
